package com.inslab.planets

val milkyDes : String = "The Milky Way is a huge collection of stars, dust and gas. It’s called a spiral galaxy because if you could view it from the top or bottom, it would look like a spinning pinwheel. The Sun is located on one of the spiral arms, about 25,000 light-years away from the center of the galaxy."
val mercuryDes : String = "Mercury is the closest planet to the sun and the smallest planet in the solar system — it is only a little larger than Earth's moon. Mercury zips around the sun in only 88 days and because it is so close to our star (about two-fifths the distance between Earth and the sun)."
val venusDes : String = "Venus is the second planet from the Sun, and is Earth's closest neighbor in the solar system. Venus is the brightest object in the sky after the Sun and the Moon, and sometimes looks like a bright star in the morning or evening sky. The planet is a little smaller than Earth, and is similar to Earth inside"
val earthDes : String = "Earth, our home planet, is the third planet from the sun. It is a water world with two-thirds of the planet covered by water. Earth's atmosphere is rich in nitrogen and oxygen and it is the only world known to harbor life."
val marsDes : String = "Mars is the fourth planet from the sun. It is a cold, desert-like planet covered in iron oxide dust that gives the planet its signature red hue. Mars shares similarities with Earth: It is rocky, has mountains, valleys and canyons, and storm"
val jupiterDes : String = "Jupiter is the fifth planet from the sun and the largest planet in the solar system. The gas giant is more than twice as massive as all the other planets combined, according to NASA (opens in new tab). "
val saturnDes : String = "Saturn is the sixth planet from the sun and is famous for its large and distinct ring system. Though Saturn is not the only planet in the solar system with ring, Galileo Galilei first studied Saturn in the early 1600s, he thought it was an object with three parts"
val uranusDes : String = "Uranus is the seventh planet from the sun and is a bit of an oddball It has clouds made of hydrogen sulfide, the same chemical that makes rotten eggs smell so foul, It rotates from east to west like Venus"
val neptuneDes : String = "Neptune is the eighth planet from the sun and is on average the coldest planet in the solar system. The average temperature of Neptune at the top of the clouds is minus 346 degrees Fahrenheit"

val milkyTag : String = "The home of our solar system"
val mercuryTag : String = "Closest planet to the sun"
val venusTag: String = "Earth's solar system twin"
val earthTag: String = "Our home planet, filled with life"
val marsTag: String = "The solar system's Red Planet"
val jupiterTag : String = "The largest planet in our solar system"
val saturnTag : String = "The ringed jewel of the solar system"
val uranusTag: String = "The sideways planet in our solar system"
val neptuneTag : String = "A giant, stormy blue planet"